from ctypes import c_bool as c_bool
from ctypes import c_int as c_int
from ctypes import c_void_p as c_void_p
from ctypes import pointer as pointer

from _typeshed import Incomplete
from OpenGL.GLES2.VERSION.GLES2_2_0 import *
from OpenGL.GLES3.VERSION.GLES3_3_0 import *

def getEGLNativeDisplay() -> None: ...
def getglEGLImageTargetTexture2DOES(): ...

glEGLImageTargetTexture2DOES: Incomplete

def str_to_fourcc(str): ...
def get_gl_extensions(): ...
def check_gl_extensions(required_extensions) -> None: ...
def get_egl_extensions(egl_display): ...
def check_egl_extensions(egl_display, required_extensions) -> None: ...
