from OpenGL.GLES2.VERSION.GLES2_2_0 import *
from OpenGL.GLES3.VERSION.GLES3_3_0 import *
from _typeshed import Incomplete
from ctypes import c_bool as c_bool, c_int as c_int, c_void_p as c_void_p, pointer as pointer

def getEGLNativeDisplay() -> None: ...
def getglEGLImageTargetTexture2DOES(): ...

glEGLImageTargetTexture2DOES: Incomplete

def str_to_fourcc(str): ...
def get_gl_extensions(): ...
def check_gl_extensions(required_extensions) -> None: ...
def get_egl_extensions(egl_display): ...
def check_egl_extensions(egl_display, required_extensions) -> None: ...
