from _typeshed import Incomplete

_log: Incomplete

class NullPreview:
    def thread_func(self, picam2) -> None: ...
    size: Incomplete
    _abort: Incomplete
    _started: Incomplete
    picam2: Incomplete
    def __init__(self, x=None, y=None, width=None, height=None, transform=None) -> None: ...
    thread: Incomplete
    def start(self, picam2) -> None: ...
    def set_overlay(self, overlay) -> None: ...
    def render_request(self, completed_request) -> None: ...
    def handle_request(self, picam2) -> None: ...
    def stop(self) -> None: ...
    def set_title_function(self, function) -> None: ...
