from _typeshed import Incomplete
from enum import Enum

class Command(Enum):
    CREATE = 1
    DELETE = 2
    FIN = 3

class QtPreviewBase:
    thread: Incomplete
    def make_picamera2_widget(picam2, width: int = 640, height: int = 480, transform=None) -> None: ...
    def get_title() -> None: ...
    previewcreateq: Incomplete
    app: Incomplete
    def thread_func(self, previewcreateq) -> None: ...
    x: Incomplete
    y: Incomplete
    width: Incomplete
    height: Incomplete
    transform: Incomplete
    def __init__(self, x=None, y=None, width: int = 640, height: int = 480, transform=None) -> None: ...
    event: Incomplete
    qpicamera2: Incomplete
    def start(self, picam2) -> None: ...
    def stop(self) -> None: ...
    def fin(self) -> None: ...
    def set_overlay(self, overlay) -> None: ...
    def set_title_function(self, function) -> None: ...

class QtPreview(QtPreviewBase):
    def make_picamera2_widget(self, picam2, width: int = 640, height: int = 480, transform=None): ...
    def get_title(self): ...

class QtGlPreview(QtPreviewBase):
    def make_picamera2_widget(self, picam2, width: int = 640, height: int = 480, transform=None): ...
    def get_title(self): ...
