from enum import Enum

from _typeshed import Incomplete

from ..outputs import Output as Output
from ..request import _MappedBuffer as _MappedBuffer

class Quality(Enum):
    VERY_LOW = 0
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    VERY_HIGH = 4

class Encoder:
    _width: int
    _height: int
    _stride: int
    _format: Incomplete
    _output: Incomplete
    _running: bool
    _name: Incomplete
    _framerate: Incomplete
    _lock: Incomplete
    firsttimestamp: Incomplete
    frame_skip_count: int
    _skip_count: int
    _output_lock: Incomplete
    audio: bool
    audio_input: Incomplete
    audio_output: Incomplete
    audio_sync: int
    _audio_start: Incomplete
    frames_encoded: int
    sync_enable: bool
    sync: Incomplete
    _first_audio_time: Incomplete
    def __init__(self, framerate: int = 30) -> None: ...
    @property
    def running(self): ...
    @property
    def width(self): ...
    @width.setter
    def width(self, value) -> None: ...
    @property
    def height(self): ...
    @height.setter
    def height(self, value) -> None: ...
    @property
    def size(self): ...
    @size.setter
    def size(self, value) -> None: ...
    @property
    def stride(self): ...
    @stride.setter
    def stride(self, value) -> None: ...
    @property
    def format(self): ...
    @format.setter
    def format(self, value) -> None: ...
    @property
    def output(self): ...
    @output.setter
    def output(self, value) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, value) -> None: ...
    def encode(self, stream, request) -> None: ...
    def _encode(self, stream, request) -> None: ...
    def _send_audio_stream(self, output) -> None: ...
    def send_streams(self, output) -> None: ...
    def _send_streams(self, output) -> None: ...
    _audio_input_container: Incomplete
    _audio_input_stream: Incomplete
    _audio_output_container: Incomplete
    _audio_output_stream: Incomplete
    _audio_thread: Incomplete
    def start(self, quality=None) -> None: ...
    def _start(self) -> None: ...
    def stop(self) -> None: ...
    def _stop(self) -> None: ...
    def outputframe(
        self,
        frame,
        keyframe: bool = True,
        timestamp=None,
        packet=None,
        audio: bool = False,
    ) -> None: ...
    def _setup(self, quality) -> None: ...
    def _timestamp(self, request): ...
    def _handle_audio_packet(self, audio_packet) -> None: ...
    def _audio_thread_func(self) -> None: ...
