from _typeshed import Incomplete

from . import Quality as Quality
from . import _hw_encoder_available as _hw_encoder_available
from .v4l2_encoder import V4L2Encoder as V4L2Encoder

class MJPEGEncoder(V4L2Encoder):
    def __init__(self, bitrate=None) -> None: ...
    def _send_streams(self, output) -> None: ...
    bitrate: Incomplete
    def _setup(self, quality) -> None: ...
    def _start(self) -> None: ...
