from _typeshed import Incomplete
from picamera2.encoders.encoder import Encoder as Encoder

class MultiEncoder(Encoder):
    threads: Incomplete
    tasks: Incomplete
    def __init__(self, num_threads: int = 4) -> None: ...
    def _send_streams(self, output) -> None: ...
    thread: Incomplete
    def _start(self) -> None: ...
    def _stop(self) -> None: ...
    def output_thread(self) -> None: ...
    def do_encode(self, request, stream): ...
    def _encode(self, stream, request) -> None: ...
    def encode_func(self, request, name): ...
