from _typeshed import Incomplete

class Allocator:
    needs_sync: bool
    sync: Incomplete
    def __init__(self) -> None: ...
    def allocate(self, libcamera_config, use_case) -> None: ...
    def buffers(self, stream) -> None: ...
    def acquire(self, bufs) -> None: ...
    def release(self, bufs) -> None: ...
    def close(self) -> None: ...

class Sync:
    __fb: Incomplete
    def __init__(self, allocator, fb, write) -> None: ...
    __mm: Incomplete
    def __enter__(self): ...
    def __exit__(self, exc_type=None, exc_value=None, exc_traceback=None) -> None: ...
