from _typeshed import Incomplete
from picamera2.allocators.allocator import Allocator as Allocator
from picamera2.allocators.allocator import Sync as Sync
from picamera2.dma_heap import DMA_BUF_IOCTL_SYNC as DMA_BUF_IOCTL_SYNC
from picamera2.dma_heap import DMA_BUF_SYNC_END as DMA_BUF_SYNC_END
from picamera2.dma_heap import DMA_BUF_SYNC_READ as DMA_BUF_SYNC_READ
from picamera2.dma_heap import DMA_BUF_SYNC_RW as DMA_BUF_SYNC_RW
from picamera2.dma_heap import DMA_BUF_SYNC_START as DMA_BUF_SYNC_START
from picamera2.dma_heap import DmaHeap as DmaHeap
from picamera2.dma_heap import dma_buf_sync as dma_buf_sync

_log: Incomplete

class DmaAllocator(Allocator):
    dmaHeap: Incomplete
    mapped_buffers: Incomplete
    mapped_buffers_used: Incomplete
    frame_buffers: Incomplete
    open_fds: Incomplete
    libcamera_fds: Incomplete
    sync: Incomplete
    def __init__(self) -> None: ...
    def allocate(self, libcamera_config, _) -> None: ...
    def buffers(self, stream): ...
    def acquire(self, buffers) -> None: ...
    def release(self, buffers) -> None: ...
    def cleanup(self) -> None: ...
    def close(self) -> None: ...
    def __del__(self) -> None: ...
    class DmaSync(Sync):
        allocator: Incomplete
        __fb: Incomplete
        __write: Incomplete
        def __init__(self, allocator, fb, write) -> None: ...
        def __enter__(self): ...
        def __exit__(
            self, exc_type=None, exc_value=None, exc_traceback=None
        ) -> None: ...
        def get_buffer(self): ...
