from .controls import Controls as Controls
from _typeshed import Incomplete

class Configuration:
    def __init__(self, d={}) -> None: ...
    def __setattr__(self, name, value) -> None: ...
    def __getattribute__(self, name): ...
    def __repr__(self) -> str: ...
    def update(self, update_dict) -> None: ...
    def make_dict(self): ...
    size: Incomplete
    def align(self, optimal: bool = True) -> None: ...

class StreamConfiguration(Configuration):
    _ALLOWED_FIELDS: Incomplete
    _FIELD_CLASS_MAP: Incomplete
    _FORWARD_FIELDS: Incomplete

class SensorConfiguration(Configuration):
    _ALLOWED_FIELDS: Incomplete
    _FIELD_CLASS_MAP: Incomplete
    _FORWARD_FIELDS: Incomplete

class CameraConfiguration(Configuration):
    _ALLOWED_FIELDS: Incomplete
    _FIELD_CLASS_MAP: Incomplete
    _FORWARD_FIELDS: Incomplete
    sensor: Incomplete
    def __init__(self, d={}, picam2=None) -> None: ...
    lores: Incomplete
    def enable_lores(self, onoff: bool = True) -> None: ...
    raw: Incomplete
    def enable_raw(self, onoff: bool = True) -> None: ...
    def align(self, optimal: bool = True) -> None: ...
