import types

from _typeshed import Incomplete

class Controls:
    def _framerates_to_durations_(framerates): ...
    def _durations_to_framerates_(durations): ...
    _VIRTUAL_FIELDS_MAP_: Incomplete
    _picam2: Incomplete
    _controls: Incomplete
    _lock: Incomplete
    def __init__(self, picam2, controls={}) -> None: ...
    def __setattr__(self, name, value) -> None: ...
    def __getattribute__(self, name): ...
    def __repr__(self) -> str: ...
    def __enter__(self): ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        tb: types.TracebackType | None,
    ) -> None: ...
    def set_controls(self, controls) -> None: ...
    def get_libcamera_controls(self): ...
    def make_dict(self): ...
