from _typeshed import Incomplete

YUV_FORMATS: Incomplete
RGB_FORMATS: Incomplete
BAYER_FORMATS: Incomplete
MONO_FORMATS: Incomplete
ALL_FORMATS = YUV_FORMATS | RGB_FORMATS | BAYER_FORMATS | MONO_FORMATS

def is_YUV(fmt: str) -> bool: ...
def is_RGB(fmt: str) -> bool: ...
def is_Bayer(fmt: str) -> bool: ...
def is_mono(fmt: str) -> bool: ...
def is_raw(fmt: str) -> bool: ...
def assert_format_valid(fmt: str) -> None: ...
