import multiprocessing as mp
import picamera2
import types
from _typeshed import Incomplete
from typing import Any, Callable

class Process:
    _send_queue: Incomplete
    _return_queue: Incomplete
    _requests_sent: Incomplete
    _timeout: Incomplete
    _thread: Incomplete
    _process: Incomplete
    def __init__(self, run: Callable[[RemoteRequest], Any], picam2: picamera2.Picamera2, init: Callable[[], None] | None = None, timeout: float | None = 30) -> None: ...
    def _return_thread(self) -> None: ...
    def send(self, request: picamera2.request.CompletedRequest, **kwargs): ...
    def close(self) -> None: ...

class _RemoteProcess(mp.Process):
    _send_queue: Incomplete
    _return_queue: Incomplete
    _return_result: bool
    _pid_fd: Incomplete
    _picam2_pid: Incomplete
    _array_cache: Incomplete
    _buffer_cache: Incomplete
    _request: Incomplete
    _helper: Incomplete
    _run: Incomplete
    _init_func: Incomplete
    def __init__(self, send_queue: mp.Queue, return_queue: mp.Queue, picam2: picamera2.Picamera2, run: Callable[[RemoteRequest], Any], init: Callable[[], None], *args, **kwargs) -> None: ...
    _syscall: Incomplete
    def _child_init(self) -> None: ...
    def run(self) -> None: ...
    def _map_fd(self, picam2_fd: int): ...
    def _capture_request(self): ...
    def _return_request(self, return_value: Any): ...

class RemoteMappedArray:
    _request: Incomplete
    _stream_name: Incomplete
    _array: Incomplete
    def __init__(self, request: RemoteRequest, stream_name: str) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, exc_traceback: types.TracebackType | None) -> None: ...
    @property
    def array(self): ...

class RemoteRequest:
    request: Incomplete
    _metadata: Incomplete
    config: Incomplete
    _array_ref_count: int
    _buffers_fd: Incomplete
    _kwargs: Incomplete
    def __init__(self, request: picamera2.request.CompletedRequest, **kwargs) -> None: ...
    def _serialize_stream(self, stream_name: str): ...
    _arrays: Incomplete
    _buffers: Incomplete
    _process: Incomplete
    def _deserialize(self, process: _RemoteProcess): ...
    def _deserialize_buffer(self, fd: int, length: int): ...
    def _create_array(self, mem, name: str): ...
    def get_metadata(self): ...
    def get_config(self): ...
    def make_buffer(self, stream_name: str): ...
    def make_array(self, stream_name: str): ...
    def make_image(self, stream_name: str): ...
    def save(self, file_output: str, name: str = 'main', format_str: str | None = None, exif_data: dict | None = None): ...
    def save_dng(self, file_output: str, name: str = 'raw'): ...

class _FakeObject:
    def __init__(self, **kwargs) -> None: ...

class _RemotePicamera2:
    camera: Incomplete
    options: Incomplete
    camera_properties: Incomplete
    def __init__(self, picam2: picamera2.Picamera2) -> None: ...

class Pool:
    _processes: Incomplete
    _process_count: Incomplete
    _process_index: int
    def __init__(self, run: Callable[[RemoteRequest], Any], count: int, picam2: picamera2.Picamera2, init: Callable[[], None] | None = None, timeout: float | None = 30) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, exc_traceback: types.TracebackType | None) -> None: ...
    def send(self, request: picamera2.request.CompletedRequest, **kwargs): ...
    def close(self) -> None: ...
