from _typeshed import Incomplete
from libcamera import Transform as Transform

class SensorFormat:
    packing: Incomplete
    bit_depth: Incomplete
    bayer_order: Incomplete
    def __init__(self, fmt_string) -> None: ...
    @property
    def format(self): ...
    @property
    def unpacked(self): ...
    @property
    def mono(self): ...
    def __repr__(self) -> str: ...
    def transform(self, transform: Transform): ...
