from _typeshed import Incomplete

def convert_from_libcamera_type(value): ...
def colour_space_to_libcamera(colour_space, format): ...

COLOUR_SPACE_TABLE: Incomplete

def colour_space_from_libcamera(colour_space): ...

_TRANSFORM_TO_ORIENTATION_TABLE: Incomplete
_ORIENTATION_TO_TRANSFORM_TABLE: Incomplete

def transform_to_orientation(transform): ...
def orientation_to_transform(orientation): ...
