name: Check code format and typing

on:
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v4
        with:
          args: "check"

      - name: Run Ruff Formatter
        if: always()
        uses: astral-sh/ruff-action@v4
        with:
          args: "format --check"

  type-check:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install .
          pip install basedpyright

      - name: Run Basedpyright
        run: basedpyright
