name: Release Spyglass

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  push_to_main:
    name: FF Merge and Bump version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Fast Forward Merge To Main
        uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
        with:
          branchtomerge: origin/develop
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        id: bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: release_body.md

      - name: Fast Forward Merge To Develop
        uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
        with:
          branchtomerge: main
          branch: develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Body
        uses: actions/upload-artifact@v4
        with:
          name: release-body.md
          path: release_body.md

  build:
    name: Build wheel and .deb
    needs: push_to_main
    uses: ./.github/workflows/build.yml
    with:
      branch: 'main'

  release:
    name: Create Release
    needs: [push_to_main, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all Artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./dist/

      - name: Move all artifact files to dist root
        run: |
          find ./dist -mindepth 2 -type f -exec mv -t ./dist {} +

      - name: Move release_body.md
        run: |
          mv ./dist/release_body.md .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release_body.md
          tag_name: ${{ needs.push_to_main.outputs.version }}
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
